### PR TITLE
chore: add script to generate puml diagrams

### PR DESCRIPTION
**Pull request by kleyow**

### CODE REVIEW

**Comment by kleyow** [comment]
@lewisdaly Not sure if we can add this to be a commit hook... :thinking:. Maintaining the current docs/ file structure won't be possible it would be more flat maybe...

Scary bash command...

**Comment by lewisdaly** [comment]
Thanks for this @kleyow - I'll play around a little more with it, maybe move it into the `./scripts` folder  to make it more readable

**Comment by lewisdaly** [comment]
At the worst, we could add a circleci check that runs this and then does a `git diff | wc -l ` to say "Hey, you didn't update the puml images"

**Comment by lewisdaly** [comment]
@kleyow I updated the script and added a circleci check.

**Review by lewisdaly — APPROVED** [review]

**Comment by lewisdaly** [comment]
Going to merge this in now since it will make my life a lot easier when updating sequences.

**Comment by kleyow** [comment]
Np. Sorry for letting this become stale.

**Comment by lewisdaly** [comment]
Thanks for your help @kleyow !

**Pull request merged**
