### PR TITLE
Copy jjgewwax/mojaloop-pisp repo to ./docs

### PR DESCRIPTION
**Pull request by lewisdaly**
It's a little messy, but I wanted to get them all across into a more central place first.

### CODE REVIEW

**Comment by lewisdaly** [comment]
Cool. @jgeewax  Please approve if you're happy and I can merge

**Comment by jgeewax** [comment]
Weird.. I did choose approve when I wrote that comment. Maybe it has to be empty...? Anyway, approved now.

**Comment by lewisdaly** [comment]
Hmm github still doesn't want me to merge it, but I think perhaps I set up the branch protection rules wrong.

**Comment by lewisdaly** [comment]
Ah I see. I didn't set up the collaborators properly. All good now. Thanks @jgeewax

**Pull request merged**
