### PR TITLE
Updated central ledger and ml adapter images.

### PR DESCRIPTION
**Pull request by kleyow**

### CODE REVIEW

**Comment by lewisdaly** [comment]
Hmm looks like the `ml-api-adapter` isn't spinning up like it should...

**Comment by kleyow** [comment]
@lewisdaly Oh, I typically wait til a build is successful til adding reviewers, guess I might of zombie-brained added. Early morning struggle.

These should be the last two services that need images other than ml-testing-toolkit/transaction-requests-service. 

@sridharvoruganti @eoln Can I leave you two to do the pisp images of ml-testing-toolkit/transaction-requests-service respectively since you guys have been working on those?

**Comment by sridharvoruganti** [comment]
@kleyow I think we can ignore ml-testing-toolkit for now, ml-testing-toolkit team has suggested to use main build by keeping new specification files  in PISP repository. So if require I will do that changes later.

**Comment by kleyow** [comment]
Oh, cool. Thanks for the update.

**Pull request merged**
