### PR TITLE
fix(puml): change pngs to svgs to fix rendering issues

### PR DESCRIPTION
**Pull request by lewisdaly**

### CODE REVIEW

**Review by sridharvoruganti — APPROVED** [review]
lgtm

**Review by elnyry-sam-k — APPROVED** [review]

**Comment by lewisdaly** [comment]
@elnyry-sam-k  I think I know why this isn't allowed to be merged. In this repo - JJ and I are docs code owners, and since this change touches the docs, it requires an approval from JJ as well.

I'll remove the separate entry for codeowners in another PR, we don't really need it at the moment.

**Comment by elnyry-sam-k** [comment]
cool, thanks Lewis :-)

**Comment by lewisdaly** [comment]
I'm going to close this - I ended up using a very different approach in the Mojaloop documentation repo, which I'd like to bring across to here.

**Pull request closed without merging**
