### PR TITLE
feat(docker-local): enable pisp-demo-svc end to end tests

### PR DESCRIPTION
**Pull request by lewisdaly**

### CODE REVIEW

**Comment by lewisdaly** [comment]
I'm building this for now to see how circleci feels about the `extra_hosts` changes.

**Comment by kleyow** [comment]
I suggest staring at the circleci terminal angrily. Worked 100% of the time for me

**Comment by lewisdaly** [comment]
> I suggest staring at the circleci terminal angrily. Worked 100% of the time for me.

Haha maybe you have a special stare that works better than mine.

**Comment by lewisdaly** [comment]
@kleyow it's finally working! CircleCI seems a little flaky to me unfortunately. Maybe we need to spin the `docker-compose up` steps into their own script with retries, although that may not really be a good solution.

**Review by kleyow — APPROVED** [review]
These are some huge and awesome QoL changes. Excited we don't have to deal with postman.

I'm guessing we will need to maintain ml-bootstrap for cases like adding new endpoints and such. From a prelimanary glance it seems really clean.

**Comment by lewisdaly** [comment]
Thanks @kleyow - yeah we will have to maintain ml-bootstrap into the future, it's currently on my own github org, but I'll add it to the mojaloop org soon so we can get ci/cd and npm releases working

**Pull request merged**
