### PR TITLE
docs: transaction callback

### PR DESCRIPTION
**Pull request by lewisdaly**
This is a document which describes the proposed design for getting transfer callbacks to the PISP after the central-ledger emits a `Transfer Fulfil Notification`

### CODE REVIEW

**Review by eoln — APPROVED** [review]
lgtm. I would stick to Mongo as CEP is already using it

**Comment by lewisdaly** [comment]
> lgtm. I would stick to Mongo as CEP is already using it

Yeah I would like to as well - we just need to be careful here since I think we need to have multiple listeners referring to a single shared object. I think we want to be able to deal with cases where we could receive both a `PUT /thirdpartyRequests/transactions/{id}/error` and a `PUT /transfers/{id}/error` at the same time.

I've added more detail to the error states and state transitions, which hopefully illustrates the way I see this listener object being created, and added to as we go along.

**Comment by lewisdaly** [comment]
Feedback from JJ:

- can the `transactionId` change? For example, if the quote or transfer fails, can the DFSP start a new quote with the _same_ `transactionRequestId` but a different `transactionId`? 

- If the `transactionId` does change (or even the `transferId` for that matter) we need to be model a one-to-many relationsip between a `transactionRequestId` and `transactionId`

**Comment by lewisdaly** [comment]
- DFSP shouldn't retry transaction - it's the PISP's responsibility to do that?
- single transactionId could have multiple transfers (e.g. multi-hop, retry failed transfers)

**Pull request merged**
